# Generated by Django 4.1 on 2024-05-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournaments", "0005_rename_number_of_games_tournament_number_of_rounds"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["-datetime", "round"]},
        ),
        migrations.AlterField(
            model_name="game",
            name="played",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="matching",
            field=models.CharField(
                choices=[
                    ("all", "All participants play every games"),
                    ("pairs", "Head to head games"),
                ],
                default="all",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="scheduling",
            field=models.CharField(
                choices=[
                    ("Continual", "Going on until deactivation"),
                    (
                        "Round-robin",
                        "Round-robin (each contestant meets every other participant)",
                    ),
                ],
                default="Continual",
                max_length=16,
            ),
        ),
    ]
