# Generated by Django 4.1 on 2022-08-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="category",
        ),
        migrations.AddField(
            model_name="tournament",
            name="Scheduling",
            field=models.CharField(
                choices=[
                    ("Continual", "Going on, without interruptions"),
                    ("Determined", "Fixed number of games"),
                    ("Round-robin", "Each contestant meets every other participant"),
                ],
                default="Continual",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="matching",
            field=models.CharField(
                choices=[
                    ("all", "All participants play every games"),
                    ("pairs", "Head to head games"),
                ],
                default="all",
                max_length=16,
                null=True,
            ),
        ),
    ]
