# Generated by Django 4.1 on 2022-08-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_remove_tournament_category_tournament_scheduling_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="Scheduling",
        ),
        migrations.AddField(
            model_name="tournament",
            name="number_of_games",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tournament",
            name="scheduling",
            field=models.CharField(
                choices=[
                    ("Continual", "Going on until deactivation"),
                    (
                        "Round-robin",
                        "Round-robin (each contestant meets every other participant)",
                    ),
                ],
                default="Continual",
                max_length=16,
                null=True,
            ),
        ),
    ]
